### ISSUE TITLE
Merge Cpplint Pull requests / fix issues

### ISSUE THREAD

**Issue by tkruse** [tkruse/cpplint#19]
@itamaro, @mattyclarkson, @massenz, @tychoish, @dirk-thomas, I took the liberty to make branches and pull requests from several outstanding PRs on https://github.com/google/styleguide. I believe that repo is practically dead, and anyway I don't see good reasons why a public linter should be kept in a single same repo as coding guidelines for various languages for Google employees.

I mention you here because you all contributed patches to cpplint. I would like to merge the changes to make a new pypi release of cpplint. The PRs need to be rebased and reviewed, possibly also adding additional tests or consolidating. I'll eagerly merge PRs that have been reviewed by any of you (except by the authors themselves).

If you would like to comment or change your own PRs, or review any of the others, that would make things go faster.

* [ ] #6 Fix wrong report for "public slots" +  #8 Quick hack for QT
* [ ] #7 The cpplint returns non-zero when there is at least one message.
* [ ] #9 Allow end-of-namespace lines that begin with whitespace.
* [ ] #10 Make output appear in the Visual Studio Error List
* [ ] #11 Fix headers ext
* [ ] #12 Python3000 (my master branch already has similar patches)
* [ ] #13 Explicit variadic constructors
* [ ] #14 Single line lambdas
* [ ] #15 Doxygen
* [ ] #16 Using namespace literals
* [ ] #17 Added the extensions option to the CPPLINT.cfg option file
* [ ] #18 Access keyword indent

Also to fix (no patch yet):
* [ ] https://github.com/google/styleguide/issues/62
* [ ] https://github.com/google/styleguide/issues/61
* [ ] https://github.com/google/styleguide/issues/14

**Comment by massenz** [comment]
@tkruse Thanks for doing that!
I'm currently traveling but will happily follow up on this later this week, or next weekend at the latest.

And, yes, I agree with you: this repo is pretty much "dead".

**Comment by mattyclarkson** [comment]
@tkruse, good work taking this up. I can rebase our stuff onto yours.

**Comment by tkruse** [comment]
@mattyclarkson : I merged most of the commits from your fork already, because it was well-tested. Only the py3000 needs merge decisions.

**Comment by dirk-thomas** [comment]
Any progress on `cpplint` is good progress :smile:

It would be good to consider PEP 8 and PEP 257 at some point (related to google/styleguide#77). Even the code being added and modified is highly inconsistent (e.g. indentation). Maybe changes can at least aim for following the recommendation if the existing code isn't updated immediately.

The conceptionally biggest problem imo is google/styleguide#78. While the proposed changes imply updating existing header guards without the definitions are simply not unique and can collide. Therefore adding support for this with an opt-in option would be good.

**Comment by massenz** [comment]
@tkruse - do you still need any work from me?
Finally back, now have time to contribute to this, if desired.

There's also this fix (from my fork of `styleguide`):
https://github.com/massenz/styleguide/commit/9c3afba6458d1b34b05fae88bdb30685dd5e7e1b

To me, the most pressing need would be to make this monster of non-PEP8-horribly-written single-file abomination into a more modular and more manageable set of modules.

**Comment by massenz** [comment]
But, I'm also wondering whether this is worth the effort, considering `clang-format` 3.8 addresses many of the reasons why we looked into using `cppstyle` instead.

Do folks have opinions, either way?

**Comment by tkruse** [comment]
@massenz , you could help by providing unit test for any of the prs. I am traveling right now, I hope to release a new version of cooling when I am back. I don't know what can go into that release, I will add least try to get all issue I marked as 'essential' in. You can look into any of those to help.
Also I consider writing regression test which get frozen versions of real life libraries, and make sure future versions of cooking report the same issues.

I currently do not consider large scale refactoring of cpplint. The Google fork still remains relevant, and I expect more people will contribute to that than to my fork. So the codebases should not diverge too much.

**Comment by tkruse** [comment]
@gueraf, if you have time, you may join the effort, several PRs still require reviews

**Comment by tkruse** [comment]
Hi everybody, this is a little mebarassing. A while ago I handed over maintenance duty to @theandrewdavis (and then forgot about it), so these PRs should all be made to https://github.com/theandrewdavis
Never worry, the work is not wasted, and I can easily recreate PRs against that repo from the work made here so far.

**Comment by tkruse** [comment]
Small update, it seems cpplint is not quite dead at google, they just do the development in their private svn and ignore github PRs:
https://github.com/google/styleguide/pull/130

**Comment by massenz** [comment]
One day late and one penny short :D
The Mesos community (my original motivation to try and fix cpplint) has
moved on to clang-format, which is what I'd also recommend.

I'm afraid I will no longer be contributing to this, just too much stuff
going on.

Thanks.

On Wednesday, May 18, 2016, Thibault Kruse notifications@github.com wrote:

> Small update, it seems cpplint is not quite dead at google, they just do
> the development in their private svn and ignore github PRs:
> google/styleguide#130 https://github.com/google/styleguide/pull/130
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/tkruse/cpplint/issues/19#issuecomment-220215942

## 

Sent from my iPhone, please forgive typoz n brvty
